<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="apples-MacBook-Pro-6.local" failures="1" tests="4" name="Default test" time="4.117" errors="0" timestamp="2024-12-10T12:35:06 IST">
  <testcase classname="testcases.UpdateOrganisationProfileTest1" name="testUpdateOrganisationProfile" time="2.464">
    <failure type="java.lang.AssertionError" message="expected:&amp;lt;Test Company&amp;gt; but was:&amp;lt;Company name should match.&amp;gt;">
      <![CDATA[java.lang.AssertionError: expected:<Test Company> but was:<Company name should match.>
at org.testng.AssertJUnit.assertEquals(AssertJUnit.java:115)
at testcases.UpdateOrganisationProfileTest1.testUpdateOrganisationProfile(UpdateOrganisationProfileTest1.java:47)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:664)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:227)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:957)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:200)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:848)
at org.testng.TestRunner.run(TestRunner.java:621)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:443)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:437)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:397)
at org.testng.SuiteRunner.run(SuiteRunner.java:336)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1280)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1200)
at org.testng.TestNG.runSuites(TestNG.java:1114)
at org.testng.TestNG.run(TestNG.java:1082)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- testUpdateOrganisationProfile -->
  <testcase classname="testcases.SendSignupOtpTest" name="testSendSignupOtp" time="0.197"/>
  <testcase classname="testcases.VerifySignupOtpTest" name="testVerifySignupOtp" time="0.135"/>
  <testcase classname="testcases.UpdateOrganisationProfileTest" name="testUpdateOrganisationProfile" time="0.29"/>
</testsuite> <!-- Default test -->
